// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"jsc-join-api/app/hospital"
	"jsc-join-api/app/join"
	"jsc-join-api/app/subdistrict"
)

// Injectors from wire.go:

func JoinModule() join.JoinController {
	subdistrictService := subdistrict.ProvideSubdistrictService()
	hospitalService := hospital.ProvideHospitalService()
	joinService := join.ProvideJoinService(subdistrictService, hospitalService)
	joinController := join.ProvideJoinController(joinService)
	return joinController
}
